### ISSUE TITLE
Inappropriate word combinations

### ISSUE THREAD

**Issue by joe2son** [emilbayes/eff-diceware-passphrase#5]
Hey.

Subjective as to whether this is a bug or not.... but for my use case (generating unique url containing 3 word phrase for a user to share) we're not that comfortable with our users seeing/sharing urls containing some of these actual generated examples:

```
extrovert-pantyhose-stupor
enlarged-fascism-tattoo
unisexual-spinster-arrogant
profuse-dad-grab
```

I don't suppose there ought to be an argument that can be passed to the `generatePassphrase` method to specify `clean` pass-phrases?

**Comment by emilbayes** [comment]
I don’t know how I would be able to do that, but the list was specifically made by EFF to try and reduce such combinations from the original diceware list. The list here is “standardised” so I will not change it but feel free to fork the repo and swap out words :) the entropy calculation requires the exact number of words in the list tho so remember to replace words instead of just deleting

**Comment by emilbayes** [comment]
I have observed some unfortunate combinations in my own use also so I’m not opposed to collaborate on a new list that could include famous last names, capitals and such to try and mitigate some of the more unfortunate words

**Comment by joe2son** [comment]
Haha! Ok, no worries -- that makes sense.

Thanks for the advice, and yes, at some point I think I will fork it, and I'll let you know so we can collab 🤝 🎉
